# Generated by Django 5.0.2 on 2025-05-15 18:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_gb', models.IntegerField(choices=[(5, '5 GB'), (10, '10 GB')], help_text='Additional storage size in GB', unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text='Monthly price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Additional Storage',
                'verbose_name_plural': 'Additional Storage Options',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('base_storage_gb', models.DecimalField(decimal_places=2, help_text='Base storage allocation in GB', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text='Monthly subscription price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('can_purchase_extra_storage', models.BooleanField(default=False, help_text='Whether this tier can purchase additional storage')),
                ('max_trusted_contacts', models.PositiveIntegerField(blank=True, help_text='Maximum number of trusted contacts (null means unlimited)', null=True)),
                ('max_beneficiaries', models.PositiveIntegerField(blank=True, help_text='Maximum number of beneficiaries (null means unlimited)', null=True)),
                ('free_storage_for_contacts_gb', models.DecimalField(decimal_places=2, default=0, help_text='Free storage allocation per trusted contact in GB', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Subscription Tier',
                'verbose_name_plural': 'Subscription Tiers',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('storage_used_bytes', models.BigIntegerField(default=0, help_text='Current storage usage in bytes', validators=[django.core.validators.MinValueValidator(0)])),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe customer ID for payment processing', max_length=100)),
                ('paypal_customer_id', models.CharField(blank=True, help_text='PayPal customer ID for payment processing', max_length=100)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('trialing', 'Trialing')], default='active', max_length=20)),
                ('subscription_end_date', models.DateTimeField(blank=True, help_text='When the current subscription period ends', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('additional_storage', models.ForeignKey(blank=True, help_text='Additional storage purchase, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.additionalstorage')),
                ('subscription_tier', models.ForeignKey(default='free', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.subscriptiontier')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#000000', help_text='Hex color code for the tag', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Tag',
                'verbose_name_plural': 'Document Tags',
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('backup_frequency_days', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('storage_warning_threshold', models.PositiveIntegerField(default=80, help_text='Percentage of storage used to trigger warning', validators=[django.core.validators.MaxValueValidator(100)])),
                ('default_document_privacy', models.CharField(choices=[('private', 'Private'), ('trusted_contacts', 'Trusted Contacts'), ('beneficiaries', 'Beneficiaries')], default='private', max_length=20)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('trusted_contact', 'Trusted Contact'), ('beneficiary', 'Beneficiary')], help_text='Role of the contact (trusted contact or beneficiary)', max_length=20)),
                ('access_level', models.CharField(choices=[('view', 'View Only'), ('edit', 'Can Edit'), ('manage', 'Can Manage')], default='view', help_text='Level of access granted', max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the access grant expires (null means no expiration)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this access grant')),
                ('contact', models.ForeignKey(help_text='User who was granted access', on_delete=django.db.models.deletion.CASCADE, related_name='granted_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who granted the access', on_delete=django.db.models.deletion.CASCADE, related_name='access_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Control',
                'verbose_name_plural': 'Access Controls',
                'indexes': [models.Index(fields=['user', 'role'], name='api_accessc_user_id_c5ceec_idx'), models.Index(fields=['contact', 'role'], name='api_accessc_contact_b14ccb_idx'), models.Index(fields=['is_active'], name='api_accessc_is_acti_5cf57a_idx')],
                'unique_together': {('user', 'contact', 'role')},
            },
        ),
        migrations.CreateModel(
            name='AccountProvisioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if provisioning failed')),
                ('storage_provisioned', models.BooleanField(default=False)),
                ('backup_schedule_created', models.BooleanField(default=False)),
                ('notification_preferences_set', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the provisioning')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Provisioning',
                'verbose_name_plural': 'Account Provisioning',
                'indexes': [models.Index(fields=['status'], name='api_account_status_f2b05e_idx'), models.Index(fields=['started_at'], name='api_account_started_c92d4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('upload', 'Upload'), ('modify', 'Modify'), ('delete', 'Delete'), ('share', 'Share'), ('revoke', 'Revoke Access')], help_text='Type of action performed', max_length=20)),
                ('file_path', models.CharField(help_text='Path to the file that was accessed/modified', max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, help_text='Size of the file in bytes', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the client')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the action')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='api_auditlo_user_id_c3bd49_idx'), models.Index(fields=['timestamp'], name='api_auditlo_timesta_da87a7_idx'), models.Index(fields=['file_path'], name='api_auditlo_file_pa_77aa0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('full', 'Full Backup'), ('incremental', 'Incremental Backup'), ('document', 'Document Backup'), ('account', 'Account Backup')], help_text='Type of backup', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, help_text='Size of the backup in bytes', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('s3_key', models.CharField(help_text='S3 object key for the backup', max_length=500, unique=True)),
                ('s3_bucket', models.CharField(help_text='S3 bucket name', max_length=255)),
                ('retention_days', models.PositiveIntegerField(default=30, help_text='Number of days to retain the backup')),
                ('error_message', models.TextField(blank=True, help_text='Error message if backup failed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the backup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['user', 'type'], name='api_backup_user_id_b7d3a2_idx'), models.Index(fields=['status'], name='api_backup_status_e3dba7_idx'), models.Index(fields=['scheduled_at'], name='api_backup_schedul_96a758_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png'])])),
                ('file_size_bytes', models.BigIntegerField(help_text='Size of the file in bytes', validators=[django.core.validators.MinValueValidator(0)])),
                ('s3_key', models.CharField(help_text='S3 object key for the file', max_length=500, unique=True)),
                ('s3_bucket', models.CharField(help_text='S3 bucket name', max_length=255)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error'), ('deleted', 'Deleted')], default='uploading', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('encryption_key', models.CharField(blank=True, help_text='Encryption key reference', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the document')),
                ('user', models.ForeignKey(help_text='Owner of the document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='documents', to='api.documenttag')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='api_documen_user_id_1eac96_idx'), models.Index(fields=['uploaded_at'], name='api_documen_uploade_c2e518_idx'), models.Index(fields=['file_type'], name='api_documen_file_ty_5d1c96_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('subscription_renewal', 'Subscription Renewal'), ('storage_warning', 'Storage Warning'), ('access_granted', 'Access Granted'), ('access_revoked', 'Access Revoked'), ('system', 'System Notification')], help_text='Type of notification', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the notification', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the notification expires', null=True)),
                ('action_url', models.URLField(blank=True, help_text='Optional URL for action button')),
                ('action_text', models.CharField(blank=True, help_text='Text for the action button', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the notification')),
                ('user', models.ForeignKey(help_text='User to notify', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'type'], name='api_notific_user_id_58bdcf_idx'), models.Index(fields=['created_at'], name='api_notific_created_238c70_idx'), models.Index(fields=['priority'], name='api_notific_priorit_c4e23f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StorageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_used_bytes', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('documents_count', models.PositiveIntegerField(default=0)),
                ('backups_count', models.PositiveIntegerField(default=0)),
                ('documents_size_bytes', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('backups_size_bytes', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Storage Usage',
                'verbose_name_plural': 'Storage Usage',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='api_storage_user_id_f6768c_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], default='active', max_length=20)),
                ('payment_provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20)),
                ('provider_subscription_id', models.CharField(help_text='Subscription ID from payment provider', max_length=100, unique=True)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('payment_method_id', models.CharField(blank=True, help_text='Payment method ID from provider', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='api.subscriptiontier')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'indexes': [models.Index(fields=['status'], name='api_subscri_status_ef9a1d_idx'), models.Index(fields=['current_period_end'], name='api_subscri_current_4ebe10_idx')],
            },
        ),
    ]
