# Generated by Django 5.0.2 on 2025-05-15 22:47

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_free_tier_additional_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('support', 'Support Staff'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', help_text='Team member role', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department or team', max_length=100)),
                ('can_manage_users', models.BooleanField(default=False, help_text='Can manage user accounts')),
                ('can_manage_subscriptions', models.BooleanField(default=False, help_text='Can manage subscriptions')),
                ('can_view_audit_logs', models.BooleanField(default=False, help_text='Can view audit logs')),
                ('can_manage_documents', models.BooleanField(default=False, help_text='Can manage all documents')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the team member')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
            bases=('api.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
