# Generated by Django 5.0.2 on 2025-05-15 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_is_staff_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_tier',
            field=models.ForeignKey(blank=True, help_text='Optional subscription tier (e.g. for superusers or team members)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.subscriptiontier'),
        ),
    ]
