# Generated by Django 5.0.2 on 2025-05-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_subscription_tier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'verbose_name': 'Subscriber Preferences', 'verbose_name_plural': 'Subscriber Preferences'},
        ),
    ]
